### PR TITLE
Added some examples

### PR DESCRIPTION
**Pull request by ashfn**

### CODE REVIEW

**Comment by CallumJohnson** [comment]
Can we update these examples to have more in-depth variable names ('player' instead of 'p'), and to function without reference to 'VortechFactions' etc.

**Comment by CallumJohnson** [comment]
In reference to the commits:
https://github.com/CallumJohnson/FactionsBridge/pull/4/commits/1aecfb9db8767ec180b7f527b89b2fd8a6100dfd
https://github.com/CallumJohnson/FactionsBridge/pull/4/commits/a18c47ad505369d14f6af1bf65ffe10018856e7b

GitHub workflows cannot be applied to this project due to the nature of the dependencies used. 
Some are local system-jars as either they are not being hosted via Maven Repositories or they are premium to obtain.

**Comment by ashfn** [comment]
> 

Yeah good idea

**Comment by ashfn** [comment]
Should be good :+1:

**Pull request closed without merging**
